name: deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup git user
      run: |
        git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
        git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - run: npm install -g yarn
    - run: yarn install --frozen-lockfile
    - run: yarn run lint
    - run: yarn run test --runInBand --no-cache
      env:
        CI: true

    - run: echo fs.inotify.max_user_watches= 65536 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
    - run: yarn deploy
